project: k3d-istio
confirm: Are you sure you want to run on {{stage}}?

# Set this if you want to carry over parent process' environment variables
carry_env: true 

#
# Variables
#
# Feel free to add options here to be used as a variable throughout
# paths.
#
opts:
  region: env:AWS_REGION    # you can get env variables with the 'env:' prefix, for default values if env not found use comma. Example: env:AWS_REGION,{DEFAULT_VALUE}
  stage: development

#
# Providers
#
providers:
  # configure only from environment
  # filter secret versioning by adding comma separating in path value (path: prod/foo/bar,<VERSION>).
  aws_secretsmanager:
    env_sync:
      path: k3d/docker



